### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [MISTAnalytics/Oribi#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text argument and return a URI Encoded string. You should use this method on oribiId when generating the url
const trackingUrl = "https://cdn.oribi.io/" + oribiId + "/oribi.js";

**Comment by MISTAnalytics** [comment]
Yes, thank you for reviewing. I updated this template, please approve.

Kind regards,

**Comment by MISTAnalytics** [comment]
I changed this, could you check?

Kind regards,
Stefan Koning

Op di 12 okt. 2021 23:57 schreef praveena-pappu ***@***.***>:
